apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-Deployment
  labels:
    app: solar-system
  namespace: solar-system-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system-container
        image: muskaan810/nodemongoapp:3c434384284ee4937cc520de7c1a3f44c3cbf596
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
           name : mongo-db-creds