apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-deployment
  labels:
    app: solar-system
  namespace: solar-system-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system-container
        image: muskaan810/nodemongoapp:$GIT_COMMIT
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
           name : mongo-db-creds