apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: solar-system-ns
spec:
  replicas: 1
  selector:
    matchLabels: { app: mongodb }
  template:
    metadata:
      labels: { app: mongodb }
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-creds
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-creds
              key: MONGO_PASSWORD
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-data-pvc