kind: Service
apiVersion: v1
metadata:
  name: mongodb-svc
  namespace: solar-system-ns
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb