apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: solar-system-ns
type: Opaque
data:
  MONGO_USERNAME: bXVza2Fhbg==               # muskaan
  MONGO_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjM=   # StrongPassword123
  MONGO_URI: bW9uZ29kYjovL211c2thYW46U3Ryb25nUGFzc3dvcmQxMjNAbW9uZ29kYi1zdmM6MjcwMTcvc29sYXJzeXN0ZW1kYj9hdXRoU291cmNlPXNvbGFyc3lzdGVtZGI=
