apiVersion: v1
kind: Service
metadata:
  name: solar-service
  namespace: solar-system-ns
spec:
  selector:
    app: solar-system
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
    
